package entities;
// Generated Feb 3, 2017 5:45:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festival generated by hbm2java
 */
@Entity
@Table(name="festival"
    ,catalog="music_fest"
)
public class Festival  implements java.io.Serializable {


     private Integer idf;
     private String name;
     private String place;
     private Date startDate;
     private Date endDate;
     private int priceDay;
     private int priceTotal;
     private int visited;

    public Festival() {
    }

    public Festival(String name, String place, Date startDate, Date endDate, int priceDay, int priceTotal, int visited) {
       this.name = name;
       this.place = place;
       this.startDate = startDate;
       this.endDate = endDate;
       this.priceDay = priceDay;
       this.priceTotal = priceTotal;
       this.visited = visited;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDF", unique=true, nullable=false)
    public Integer getIdf() {
        return this.idf;
    }
    
    public void setIdf(Integer idf) {
        this.idf = idf;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="place", nullable=false)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDate", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDate", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="priceDay", nullable=false)
    public int getPriceDay() {
        return this.priceDay;
    }
    
    public void setPriceDay(int priceDay) {
        this.priceDay = priceDay;
    }

    
    @Column(name="priceTotal", nullable=false)
    public int getPriceTotal() {
        return this.priceTotal;
    }
    
    public void setPriceTotal(int priceTotal) {
        this.priceTotal = priceTotal;
    }

    
    @Column(name="visited", nullable=false)
    public int getVisited() {
        return this.visited;
    }
    
    public void setVisited(int visited) {
        this.visited = visited;
    }




}


