package entities;
// Generated Feb 15, 2017 4:20:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festivals generated by hbm2java
 */
@Entity
@Table(name="festivals"
    ,catalog="pia_project_db"
)
public class Festivals  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String place;
     private Date startDate;
     private Date endDate;
     private int costDay;
     private int costAll;
     private int userTicketDay;
     private int numTicketsDay;
     private String status;
     private int numVisits;

    public Festivals() {
    }

    public Festivals(String name, String place, Date startDate, Date endDate, int costDay, int costAll, int userTicketDay, int numTicketsDay, String status, int numVisits) {
       this.name = name;
       this.place = place;
       this.startDate = startDate;
       this.endDate = endDate;
       this.costDay = costDay;
       this.costAll = costAll;
       this.userTicketDay = userTicketDay;
       this.numTicketsDay = numTicketsDay;
       this.status = status;
       this.numVisits = numVisits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="place", nullable=false)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="cost_day", nullable=false)
    public int getCostDay() {
        return this.costDay;
    }
    
    public void setCostDay(int costDay) {
        this.costDay = costDay;
    }

    
    @Column(name="cost_all", nullable=false)
    public int getCostAll() {
        return this.costAll;
    }
    
    public void setCostAll(int costAll) {
        this.costAll = costAll;
    }

    
    @Column(name="user_ticket_day", nullable=false)
    public int getUserTicketDay() {
        return this.userTicketDay;
    }
    
    public void setUserTicketDay(int userTicketDay) {
        this.userTicketDay = userTicketDay;
    }

    
    @Column(name="num_tickets_day", nullable=false)
    public int getNumTicketsDay() {
        return this.numTicketsDay;
    }
    
    public void setNumTicketsDay(int numTicketsDay) {
        this.numTicketsDay = numTicketsDay;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="num_visits", nullable=false)
    public int getNumVisits() {
        return this.numVisits;
    }
    
    public void setNumVisits(int numVisits) {
        this.numVisits = numVisits;
    }




}


