package entities;
// Generated Feb 3, 2017 5:23:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Performer generated by hbm2java
 */
@Entity
@Table(name="performer"
    ,catalog="music_fest"
)
public class Performer  implements java.io.Serializable {


     private Integer idp;
     private String name;
     private Date startDate;
     private Date endDate;
     private Date startTime;
     private Date endTime;
     private int idf;

    public Performer() {
    }

    public Performer(String name, Date startDate, Date endDate, Date startTime, Date endTime, int idf) {
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.startTime = startTime;
       this.endTime = endTime;
       this.idf = idf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDP", unique=true, nullable=false)
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDate", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDate", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="startTime", nullable=false, length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="endTime", nullable=false, length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="IDF", nullable=false)
    public int getIdf() {
        return this.idf;
    }
    
    public void setIdf(int idf) {
        this.idf = idf;
    }




}


