package entities;
// Generated Feb 15, 2017 4:20:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservations generated by hbm2java
 */
@Entity
@Table(name="reservations"
    ,catalog="pia_project_db"
)
public class Reservations  implements java.io.Serializable {


     private ReservationsId id;
     private String status;
     private Date date;

    public Reservations() {
    }

    public Reservations(ReservationsId id, String status, Date date) {
       this.id = id;
       this.status = status;
       this.date = date;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="username", column=@Column(name="username", nullable=false) ), 
        @AttributeOverride(name="idTicket", column=@Column(name="id_ticket", nullable=false) ) } )
    public ReservationsId getId() {
        return this.id;
    }
    
    public void setId(ReservationsId id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


