package entities;
// Generated Feb 3, 2017 5:45:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="music_fest"
)
public class Reservation  implements java.io.Serializable {


     private Integer idr;
     private String user;
     private int idt;
     private String status;

    public Reservation() {
    }

    public Reservation(String user, int idt, String status) {
       this.user = user;
       this.idt = idt;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDR", unique=true, nullable=false)
    public Integer getIdr() {
        return this.idr;
    }
    
    public void setIdr(Integer idr) {
        this.idr = idr;
    }

    
    @Column(name="user", nullable=false)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="IDT", nullable=false)
    public int getIdt() {
        return this.idt;
    }
    
    public void setIdt(int idt) {
        this.idt = idt;
    }

    
    @Column(name="status", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


