package entities;
// Generated Feb 3, 2017 5:45:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
    ,catalog="music_fest"
)
public class Ticket  implements java.io.Serializable {


     private Integer idt;
     private int nubmer;
     private Date date;
     private int idf;

    public Ticket() {
    }

	
    public Ticket(int nubmer, int idf) {
        this.nubmer = nubmer;
        this.idf = idf;
    }
    public Ticket(int nubmer, Date date, int idf) {
       this.nubmer = nubmer;
       this.date = date;
       this.idf = idf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDT", unique=true, nullable=false)
    public Integer getIdt() {
        return this.idt;
    }
    
    public void setIdt(Integer idt) {
        this.idt = idt;
    }

    
    @Column(name="nubmer", nullable=false)
    public int getNubmer() {
        return this.nubmer;
    }
    
    public void setNubmer(int nubmer) {
        this.nubmer = nubmer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="IDF", nullable=false)
    public int getIdf() {
        return this.idf;
    }
    
    public void setIdf(int idf) {
        this.idf = idf;
    }




}


