package entities;
// Generated Feb 15, 2017 4:20:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="pia_project_db"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String surname;
     private String email;
     private String phone;
     private int role;
     private int numResAttempts;

    public Users() {
    }

    public Users(String username, String password, String name, String surname, String email, String phone, int role, int numResAttempts) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.phone = phone;
       this.role = role;
       this.numResAttempts = numResAttempts;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", nullable=false)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", nullable=false)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="role", nullable=false)
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }

    
    @Column(name="num_res_attempts", nullable=false)
    public int getNumResAttempts() {
        return this.numResAttempts;
    }
    
    public void setNumResAttempts(int numResAttempts) {
        this.numResAttempts = numResAttempts;
    }




}


